default:
  tags: [homelab]
  image: netauto:local

variables:
  ANSIBLE_CONFIG: "$CI_PROJECT_DIR/ansible.cfg"
  INV: "inventories/lab/hosts.ini"

stages:
  - build
  - prevalidation
  - deploy
  - postvalidation

lint-yaml:
  stage: build
  script:
    - yamllint inventories/ playbooks/

validate-vars:
  stage: build
  script:
    - python scripts/validate_vars.py

reach-devices:
  stage: prevalidation
  script:
    - ansible -i $INV ios -m cisco.ios.ios_facts -a "gather_subset=min"

checkpoint:
  stage: prevalidation
  script:
    - ansible-playbook -i $INV playbooks/quickies/rollback_checkpoint.yml
  artifacts:
    paths: [backups/checkpoints/]
    expire_in: 30 days

check-ospf:
  stage: prevalidation
  script:
    - ansible-playbook -i $INV playbooks/routing/ospf/configure_ospf.yml --check | tee check-ospf.txt
  artifacts:
    paths: [check-ospf.txt]
    expire_in: 1 week
    when: always

deploy-ospf:
  stage: deploy
  when: manual
  environment:
    name: lab
  script:
    - ansible-playbook -i $INV playbooks/routing/ospf/configure_ospf.yml

verify-ospf:
  stage: postvalidation
  script:
    - ansible-playbook -i $INV playbooks/postvalidation/verify_ospf.yml

rollback:
  stage: postvalidation
  when: on_failure
  script:
    - ansible-playbook -i $INV playbooks/quickies/rollback_replace.yml