---
- name: Configure IOS OSPF
  hosts: ios_ospf_routers
  gather_facts: false

  tasks:
    - name: Configure OSPF network statements
      cisco.ios.ios_config:
        parents:
          - "router ospf {{ prod_ospf_process_id }}"
        lines:
          - "router-id {{ router_id }}"
          - "network {{ item.ip_address }} 0.0.0.255 area {{ item.ospf_area | default(ospf_area) }}"
          - "log-adjacency-changes"
        match: line
      loop: "{{ ospf_interfaces }}"
      when: item.ospf_enabled | default(false)

    - name: Configure passive interfaces
      cisco.ios.ios_config:
        parents:
          - "router ospf {{ prod_ospf_process_id }}"
        lines:
          - "passive-interface {{ item.name }}"
        match: line
      loop: "{{ ospf_interfaces }}"
      when: item.passive | default(false)

    - name: Save running config if modified
      cisco.ios.ios_config:
        save_when: modified
