---
- name: Configure stub areas
  hosts: ios_ospf_routers
  gather_facts: false

  tasks:
  - name: Configure Stub Areas
    cisco.ios.ios_config:
      parents:
        - "router ospf {{ prod_ospf_process_id }}"
      lines:
        - "area {{ area.area_id }} stub"
      match: line
    loop: "{{ ospf_areas | default([]) }}"
    loop_control:
      loop_var: area
    when: area.type == "stub"

  - name: Configure NSSA areas
    cisco.ios.ios_config:
      parents:
        - "router ospf {{ prod_ospf_process_id }}"
      lines:
        - "area {{ area.area_id }} nssa"
      match: line
    loop: "{{ ospf_areas | default([]) }}"
    loop_control:
      loop_var: area
    when: area.type == "nssa"
