---
- name: Write memory on IOS devices
  hosts: ios
  gather_facts: false

  tasks:
    - name: Save IOS running-config to startup-config
      cisco.ios.ios_config:
        save_when: always


- name: Write memory on ASA devices
  hosts: asa_firewalls
  gather_facts: false

  tasks:
    - name: Save ASA running-config to startup-config
      cisco.asa.asa_command:
        commands:
          - write memory