---
#base settings
ansible_network_os: cisco.ios.ios

#tells it to enter priv exec
ansible_become: true
ansible_become_method: enable

#hard coded variables for vrfs
mgmt_vrf_vlan: 10
prof_vrf_vlan: 900