---
restconf:
  - host: 10.8.2.254
  - username: admin
  - password: admin

#BGP Configuration Modules
bgp_af:
  as_number: '65513'
  address_family:
    - afi: ipv4
      safi: unicast
      neighbors:
        - neighbor_address: 10.20.20.1
          activate: true
          route_maps:
            - name: ASN_65512
              out: true
      networks:
        - address: 9.9.9.9
          mask: 255.255.255.255

bgp_global:
  as_number: '65513'
  bgp:
    default:
      ipv4_unicast: true
      route_target:
        filter: true
    log_neighbor_changes: true
  neighbors:
    - neighbor_address: 10.20.20.1
      remote_as: '65512'

#Route-policy Configuration
prefix_lists:
  - afi: ipv4
    prefix_lists:
      - name: ASN_65512
        entries:
          - sequence: 10
            action: permit
            prefix: 10.0.16.0/20

route_maps:
  - route_map: ASN_65512
    entries:
      - sequence: 10
        action: permit
        match:
          ip:
            address:
              prefix_lists:
                - ASN_65512

#VRF Configuration
vrf_af:
  - name: MGMT
    address_families:
      - afi: ipv4
        safi: unicast
vrf_global:
  vrfs:
    - name: MGMT
vrf_ifaces:
  - name: Loopback10
    vrf_name: MGMT
  - name: Loopback900
  - name: GigabitEthernet0/1
    vrf_name: MGMT
  - name: GigabitEthernet0/2
  - name: GigabitEthernet0/3
  - name: GigabitEthernet0/3.10
    vrf_name: MGMT

#Interfaces Configuration
interfaces:
  - name: GigabitEthernet0/1
    enabled: true
  - name: GigabitEthernet0/2
    enabled: true
  - name: GigabitEthernet0/2.900
    enabled: true
  - name: GigabitEthernet0/3
    enabled: true
  - name: GigabitEthernet0/3.10
    enabled: true
  - name: Loopback10
    enabled: true
  - name: Loopback900
    enabled: true
l2_ifaces:
  - name: Loopback10
  - name: Loopback900
  - name: GigabitEthernet0/1
  - name: GigabitEthernet0/2
  - name: GigabitEthernet0/2.900
    encapsulation:
      type: dot1Q
      vlan_id: 900
  - name: GigabitEthernet0/3
  - name: GigabitEthernet0/3.10
    encapsulation:
      type: dot1Q
      vlan_id: 10

l3_ifaces:
  - name: GigabitEthernet0/1
    ipv4:
      - address: 192.168.50.23/24
        secondary: true
      - address: 192.168.50.22/24
  - name: GigabitEthernet0/2
    ipv4:
      - address: 10.0.3.1/30
  - name: GigabitEthernet0/2.900
    ipv4:
      - address: 10.20.20.2/30
  - name: GigabitEthernet0/3
  - name: GigabitEthernet0/3.10
    ipv4:
      - address: 10.8.1.254/24
  - name: Loopback10
    ipv4:
      - address: 10.8.2.254/32
  - name: Loopback900
    ipv4:
      - address: 9.9.9.9/32
