---
router_id: 10.0.26.1

restconf:
  host: 10.8.2.1

#BGP Configuration Modules
bgp_af:
  address_family:
    - afi: ipv4
      neighbors:
        - neighbor_address: 10.20.20.2
          activate: true
          route_maps:
            - name: WAN_out
              out: true
        - neighbor_address: 10.30.30.2
          activate: true
      networks:
        - address: 10.0.24.0
          mask: 255.255.255.0
        - address: 10.0.26.1
          mask: 255.255.255.255
        - address: 10.0.28.0
          mask: 255.255.255.252
      safi: unicast
  as_number: '65512'

bgp_global:
  as_number: '65512'
  bgp:
    default:
      ipv4_unicast: true
      route_target:
        filter: true
    log_neighbor_changes: true
  neighbors:
    - neighbor_address: 10.30.30.2
      remote_as: '65514'
      description: DMZ_rtr
    - neighbor_address: 10.20.20.2
      remote_as: '65513'
      description: inet_rtr

#OSPF Configuration Modules
ospf_ifaces:
  - name: Loopback900
    address_family:
      - afi: ipv4
        process:
          id: 900
          area_id: "0"

  - name: GigabitEthernet1.900
    address_family:
      - afi: ipv4
        process:
          id: 900
          area_id: "0"
        network:
          broadcast: true
  - name: GigabitEthernet2
  - name: GigabitEthernet2.10
  - name: GigabitEthernet2.900
    address_family:
      - afi: ipv4
        process:
          id: 900
          area_id: "1"
        network:
          point_to_point: true
  - name: GigabitEthernet3
  - name: GigabitEthernet3.11
  - name: GigabitEthernet4

ospf_mgmt:
  processes:
    - process_id: 1
      router_id: "10.8.2.1"
      vrf: "MGMT"
      network:
        - address: "0.0.0.0"
          area: "0"
          wildcard_bits: "255.255.255.255"

ospf_cfg:
  processes:
    - process_id: 900
      router_id: "10.0.26.1"
      areas:
        - area_id: "1"
          stub:
            set: true
            no_summary: true
      passive_interfaces:
        interface:
          name:
            - "Loopback900"
          set_interface: true

#Route-policy Configuration
prefix_lists:
  - afi: ipv4
    prefix_lists:
      - name: ASN_65513
        entries:
          - sequence: 10
            action: permit
            prefix: 10.0.0.0/20
      - name: OSPF_TO_BGP_PREFIXES
        entries:
          - sequence: 10
            action: permit
            prefix: 10.0.16.0/20
            le: 32
      - name: Test_prefix_1
        entries:
          - sequence: 20
            action: permit
            prefix: 10.20.16.0/20
            le: 32
route_maps:
  - route_map: ASN_65513
    entries:
      - sequence: 10
        action: permit
        match:
          ip:
            address:
              prefix_lists:
                - ASN_65513
        set:
          local_preference: 110
  - route_map: OSPF_TO_BGP
    entries:
      - sequence: 10
        action: permit
        match:
          ip:
            address:
              prefix_lists:
                - OSPF_TO_BGP_PREFIXES
      - sequence: 20
        action: permit
        match:
          ip:
            address:
              prefix_lists:
                - Test_prefix_1
  - route_map: WAN_out
    entries:
      - sequence: 10
        action: permit
        match:
          ip:
            address:
              prefix_lists:
                - OSPF_TO_BGP_PREFIXES
      - sequence: 20
        action: permit

#VRF Configuration
vrf_af:
  - name: MGMT
    address_families:
      - afi: ipv4
        safi: unicast
vrf_global:
  vrfs:
    - name: MGMT
vrf_ifaces:
  - name: Loopback10
    vrf_name: MGMT
  - name: Loopback900
  - name: GigabitEthernet1
  - name: GigabitEthernet1.10
    vrf_name: MGMT
  - name: GigabitEthernet1.900
  - name: GigabitEthernet2
  - name: GigabitEthernet2.10
    vrf_name: MGMT
  - name: GigabitEthernet2.900
  - name: GigabitEthernet3
  - name: GigabitEthernet3.11
    vrf_name: MGMT
  - name: GigabitEthernet4

#Interface Configuration
interfaces:
  - name: GigabitEthernet1
    enabled: true
  - name: GigabitEthernet1.10
    enabled: true
  - name: GigabitEthernet1.900
    description: Link to Broadcast
    enabled: true
  - name: GigabitEthernet2
    enabled: true
  - name: GigabitEthernet2.10
    enabled: true
  - name: GigabitEthernet2.900
    description: Link to R5
    enabled: true
  - name: GigabitEthernet3
    enabled: true
  - name: GigabitEthernet3.11
    enabled: true
  - name: GigabitEthernet3.900
    enabled: true
  - name: GigabitEthernet4
    description: BGP transit to inet rtr ASN65513
    enabled: true
  - name: GigabitEthernet4.900
    description: PROD BGP transit to inet rtr ASN65513
    enabled: true
  - name: Loopback10
    enabled: true
  - name: Loopback900
    description: R1 Router ID
    enabled: true

l2_ifaces:
  - name: Loopback10
  - name: Loopback900
    encapsulation:
      type: dot1Q
      vlan_id: 900
  - name: GigabitEthernet1
  - name: GigabitEthernet1.10
    encapsulation:
      type: dot1Q
      vlan_id: 10
  - name: GigabitEthernet1.900
    encapsulation:
      type: dot1Q
      vlan_id: 900
  - name: GigabitEthernet2
  - name: GigabitEthernet2.10
    encapsulation:
      type: dot1Q
      vlan_id: 10
  - name: GigabitEthernet2.900
    encapsulation:
      type: dot1Q
      vlan_id: 900
  - name: GigabitEthernet3
  - name: GigabitEthernet3.11
    encapsulation:
      type: dot1Q
      vlan_id: 11
  - name: GigabitEthernet3.900
    encapsulation:
      type: dot1Q
      vlan_id: 900
  - name: GigabitEthernet4
  - name: GigabitEthernet4.900
    encapsulation:
      type: dot1Q
      vlan_id: 900

l3_ifaces:
  - name: GigabitEthernet1
  - name: GigabitEthernet1.10
    ipv4:
      - address: 10.8.1.100/24
  - name: GigabitEthernet1.900
    ipv4:
      - address: 10.0.24.1/24
  - name: GigabitEthernet2
  - name: GigabitEthernet2.10
    ipv4:
      - address: 10.8.3.1/30
  - name: GigabitEthernet2.900
    ipv4:
      - address: 10.0.28.2/30
  - name: GigabitEthernet3
  - name: GigabitEthernet3.11
    ipv4:
      - address: 10.8.3.17/30
  - name: GigabitEthernet3.900
    ipv4:
      - address: 10.30.30.1/30
  - name: GigabitEthernet4
    ipv4:
      - address: 10.0.3.2/24
  - name: GigabitEthernet4.900
    ipv4:
      - address: 10.20.20.1/30
  - name: Loopback10
    ipv4:
      - address: 10.8.2.1/32
  - name: Loopback900
    ipv4:
      - address: 10.0.26.1/32
