---
router_id: 10.0.26.1

restconf:
  host: 10.8.2.1

bgp:
  asn: 65512
  update_source: Loopback900

  redistribute:
    ospf:
      enabled: true
      process_id: 900
      route_map: OSPF_TO_BGP

  prefix_lists:
    - name: OSPF_TO_BGP_PREFIXES
      entries:
        - seq: 10
          action: permit
          prefix: 10.0.16.0/20
          le: 32

  route_maps:
    - name: BLOCK_OSPF_TO_IBGP
      entries:
        - seq: 10
          action: deny

    - name: SEND_OSPF_TO_EBGP
      entries:
        - seq: 10
          action: permit
          match_prefix_list: OSPF_TO_BGP_PREFIXES

    - name: OSPF_TO_BGP
      entries:
        - seq: 10
          action: permit
          match_prefix_list: OSPF_TO_BGP_PREFIXES
  networks:
    - number: 10.0.24.0
      mask: 255.255.255.0

    - number: 10.0.28.0
      mask: 255.255.255.252

    - number: 10.0.3.0
      mask: 255.255.255.0

    - number: 10.0.26.1
      mask: 255.255.255.255

  neighbors:
    - name: R4
      peer_ip: 10.0.26.3
      remote_as: 65512
      multihop: true
      outbound_route_map: BLOCK_OSPF_TO_IBGP

    - name: inet_rtr
      peer_ip: 10.0.3.1
      remote_as: 65513
      outbound_route_map: SEND_OSPF_TO_EBGP

ospf:
  abr: true
  asbr: true

  ospf_areas:
    - area_id: 0
      type: backbone

    - area_id: 1
      type: stub
      no_summary: true

  ospf_interfaces:
    - name: GigabitEthernet1.900
      description: Link to Broadcast
      ip_address: 10.0.24.1
      subnet_mask: 255.255.255.0
      ospf_enabled: true
      passive: false
      stub: false
      ospf_area: 0
      istagged: true
      vlan_tag: 900
      process_id: 900

    - name: GigabitEthernet2.900
      description: Link to R5
      ip_address: 10.0.28.2
      subnet_mask: 255.255.255.252
      ospf_enabled: true
      passive: false
      stub: true
      stubtype: stub
      ospf_area: 1
      istagged: true
      vlan_tag: 900

    - name: Loopback900
      description: R1 Router ID
      ip_address: 10.0.26.1
      subnet_mask: 255.255.255.255
      ospf_enabled: true
      passive: true
      stub: false
      ospf_area: 0
