---
router_id: 10.0.26.1

restconf:
  host: 10.8.2.1

bgp:
  asn: 65512
  update_source: Loopback900

  redistribute:
    ospf:
      enabled: true
      process_id: 900
      route_map: OSPF_TO_BGP

  prefix_lists:
    - name: OSPF_TO_BGP_PREFIXES
      entries:
        - seq: 10
          action: permit
          prefix: 10.0.16.0/20
          le: 32

  route_maps:
    - name: BLOCK_OSPF_TO_IBGP
      entries:
        - seq: 10
          action: deny

    - name: SEND_OSPF_TO_EBGP
      entries:
        - seq: 10
          action: permit
          match_prefix_list: OSPF_TO_BGP_PREFIXES

    - name: OSPF_TO_BGP
      entries:
        - seq: 10
          action: permit
          match_prefix_list: OSPF_TO_BGP_PREFIXES
  networks:
    - number: 10.0.24.0
      mask: 255.255.255.0

    - number: 10.0.28.0
      mask: 255.255.255.252

    - number: 10.0.3.0
      mask: 255.255.255.0

    - number: 10.0.26.1
      mask: 255.255.255.255

  neighbors:
    - name: R4
      peer_ip: 10.0.26.3
      remote_as: 65512
      multihop: true
      outbound_route_map: BLOCK_OSPF_TO_IBGP

    - name: inet_rtr
      peer_ip: 10.0.3.1
      remote_as: 65513
      outbound_route_map: SEND_OSPF_TO_EBGP

ospf_ifaces:
  - name: Loopback900
    address_family:
      - afi: ipv4
        process:
          id: 900
          area_id: 0

  - name: GigabitEthernet1.900
    address_family:
      - afi: ipv4
        process:
          id: 900
          area_id: 0
  - name: GigabitEthernet2
  - name: GigabitEthernet2.10
  - name: GigabitEthernet2.900
    address_family:
      - afi: ipv4
        process:
          id: 900
          area_id: 0
  - name: GigabitEthernet3
  - address_family:
      - afi: ipv4
        network:
          point_to_point: true
  - name: GigabitEthernet3.11
  - name: GigabitEthernet4

ospf_mgmt:
  processes:
    - process_id: 1
      router_id: "10.8.2.1"
      vrf: "MGMT"
      network:
        - address: "0.0.0.0"
          area: "0"
          wildcard_bits: "255.255.255.255"

ospf_cfg:
  processes:
    - process_id: 900
      router_id: "10.0.26.1"
      areas:
        - area_id: 1
          stub:
            set: true
            no_summary: true
      passive_interfaces:
        interface:
          name:
            - "Loopback900"
          set_interface: true
