---
router_id: 10.0.26.4

restconf:
  host: 10.8.2.4

interfaces:
  - name: GigabitEthernet1
    enabled: true
  - name: GigabitEthernet1.10
    enabled: true
  - name: GigabitEthernet1.900
    description: Link to R2
    enabled: true
  - name: GigabitEthernet2
    enabled: true
  - name: GigabitEthernet2.10
    enabled: true
  - name: GigabitEthernet2.900
    description: Link to R3
    enabled: true
  - name: GigabitEthernet3
    enabled: true
  - name: GigabitEthernet3.13
    enabled: true
  - name: GigabitEthernet3.23
    description: Link to FW
    enabled: true
  - name: GigabitEthernet4
    enabled: false
  - name: Loopback10
    enabled: true
  - name: Loopback900
    description: R4 Router ID
    enabled: true
l2_ifaces:
  - name: Loopback10
  - name: Loopback900
  - name: GigabitEthernet1
  - name: GigabitEthernet1.10
    encapsulation:
      type: dot1Q
      vlan_id: 10
  - name: GigabitEthernet1.900
    encapsulation:
      type: dot1Q
      vlan_id: 900
  - name: GigabitEthernet2
  - name: GigabitEthernet2.10
    encapsulation:
      type: dot1Q
      vlan_id: 10
  - name: GigabitEthernet2.900
    encapsulation:
      type: dot1Q
      vlan_id: 900
  - name: GigabitEthernet3
  - name: GigabitEthernet3.13
    encapsulation:
      type: dot1Q
      vlan_id: 13
  - name: GigabitEthernet3.23
    encapsulation:
      type: dot1Q
      vlan_id: 23
  - name: GigabitEthernet4
l3_ifaces:
  - name: GigabitEthernet1
  - name: GigabitEthernet1.10
    ipv4:
      - address: 10.8.3.10/30
  - name: GigabitEthernet1.900
    ipv4:
      - address: 10.0.30.5/30
  - name: GigabitEthernet2
  - name: GigabitEthernet2.10
    ipv4:
      - address: 10.8.3.14/30
  - name: GigabitEthernet2.900
    ipv4:
      - address: 10.0.30.1/30
  - name: GigabitEthernet3
  - name: GigabitEthernet3.13
    ipv4:
      - address: 10.8.3.25/30
  - name: GigabitEthernet3.23
    ipv4:
      - address: 10.0.34.66/30
  - name: GigabitEthernet4
  - name: Loopback10
    ipv4:
      - address: 10.8.2.4/32
  - name: Loopback900
    ipv4:
      - address: 10.0.26.4/32

#BGP Configuration Modules
bgp_af:
  address_family:
    - afi: ipv4
      neighbors:
        - activate: true
          neighbor_address: 10.0.26.1
      networks:
        - address: 10.0.30.0
          mask: 255.255.255.252
        - address: 10.0.30.4
          mask: 255.255.255.252
      redistribute:
        - ospf:
            process_id: 900
            route_map: OSPF_TO_BGP
      safi: unicast
  as_number: '65512'

bgp_global:
  as_number: '65512'
  bgp:
    default:
      ipv4_unicast: true
      route_target:
        filter: true
    log_neighbor_changes: true
  neighbors:
    - neighbor_address: 10.0.26.1
      remote_as: '65512'

#OSPF Configuration Modules
ospf_cfg:
  processes:
    - network:
        - address: 0.0.0.0
          area: '0'
          wildcard_bits: 255.255.255.255
      process_id: 1
      router_id: 10.8.2.4
      vrf: MGMT
    - areas:
        - area_id: '2'
          nssa:
            set: true
      passive_interfaces:
        interface:
          name:
            - Loopback900
          set_interface: true
      process_id: 900
      router_id: 10.0.26.4

ospf_ifaces:
  - name: Loopback10
  - name: Loopback900
    address_family:
      - afi: ipv4
        process:
          id: 900
          area_id: 2
  - name: GigabitEthernet1
  - name: GigabitEthernet1.900
    address_family:
      - afi: ipv4
        process:
          id: 900
          area_id: 2
        network:
          point_to_point: true
  - name: GigabitEthernet2
  - name: GigabitEthernet2.900
    address_family:
      - afi: ipv4
        process:
          id: 900
          area_id: 2
        network:
          point_to_point: true
  - name: GigabitEthernet3
  - name: GigabitEthernet3.13
  - name: GigabitEthernet3.23
    address_family:
      - afi: ipv4
        process:
          id: 900
          area_id: 2
        network:
          point_to_point: true
  - name: GigabitEthernet4

#Route-policy Configuration
prefix_lists:
  - afi: ipv4
    prefix_lists:
      - name: ASN_65513
        entries:
          - sequence: 10
            action: permit
            prefix: 10.0.0.0/20
      - name: OSPF_TO_BGP_PREFIXES
        entries:
          - sequence: 10
            action: permit
            prefix: 10.0.16.0/20
            le: 32
      - name: Test_prefix_1
        entries:
          - sequence: 20
            action: permit
            prefix: 10.20.16.0/20
            le: 32
route_maps:
  - route_map: ASN_65513
    entries:
      - sequence: 10
        action: permit
        match:
          ip:
            address:
              prefix_lists:
                - ASN_65513
        set:
          local_preference: 110
  - route_map: OSPF_TO_BGP
    entries:
      - sequence: 10
        action: permit
        match:
          ip:
            address:
              prefix_lists:
                - OSPF_TO_BGP_PREFIXES
      - sequence: 20
        action: permit
        match:
          ip:
            address:
              prefix_lists:
                - Test_prefix_1
  - route_map: WAN_out
    entries:
      - sequence: 10
        action: permit
        match:
          ip:
            address:
              prefix_lists:
                - OSPF_TO_BGP_PREFIXES
      - sequence: 20
        action: permit

#VRF Configuration
vrf_af:
  - name: MGMT
    address_families:
      - afi: ipv4
        safi: unicast
vrf_global:
  vrfs:
    - name: MGMT
vrf_ifaces:
  - name: Loopback10
    vrf_name: MGMT
  - name: Loopback900
  - name: GigabitEthernet1
  - name: GigabitEthernet1.10
    vrf_name: MGMT
  - name: GigabitEthernet1.900
  - name: GigabitEthernet2
  - name: GigabitEthernet2.10
    vrf_name: MGMT
  - name: GigabitEthernet2.900
  - name: GigabitEthernet3
  - name: GigabitEthernet3.13
    vrf_name: MGMT
  - name: GigabitEthernet3.23
  - name: GigabitEthernet4
