---
router_id: 10.0.26.4

restconf:
  host: 10.8.2.4

bgp:
  asn: 65512
  update_source: Loopback900

  redistribute:
    ospf:
      enabled: false
      process_id: 900
      route_map: OSPF_TO_BGP

  prefix_lists:
    - name: OSPF_TO_BGP_PREFIXES
      entries:
        - seq: 10
          action: permit
          prefix: 10.0.16.0/20
          le: 32

  route_maps:
    - name: OSPF_TO_BGP
      entries:
        - seq: 10
          action: permit
          match_prefix_list: OSPF_TO_BGP_PREFIXES

  networks:
    - number: 10.0.30.4
      mask: 255.255.255.252
  
    - number: 10.0.30.0
      mask: 255.255.255.252
  
    - number: 10.0.34.64
      mask: 255.255.255.252

  
  neighbors:
    - name: R1
      peer_ip: 10.0.26.1
      remote_as: 65512
      multihop: true

ospf:
  abr: true
  asbr: true

  ospf_areas:
    - area_id: 0
      type: backbone
    - area_id: 2
      type: nssa

  ospf_interfaces:
    - name: GigabitEthernet2.900
      description: Link to R3
      ip_address: 10.0.30.1
      subnet_mask: 255.255.255.252
      ospf_enabled: true
      passive: false
      stub: false
      ospf_area: 0
      istagged: true
      vlan_tag: 900

    - name: GigabitEthernet1.900
      description: Link to R2
      ip_address: 10.0.30.5
      subnet_mask: 255.255.255.252
      ospf_enabled: true
      passive: false
      stub: false
      ospf_area: 2
      istagged: true
      vlan_tag: 900

    - name: GigabitEthernet3.23
      description: Link to FW
      ip_address: 10.0.34.66
      subnet_mask: 255.255.255.252
      ospf_enabled: true
      passive: false
      stub: false
      ospf_area: 0
      istagged: true
      vlan_tag: 23

    - name: Loopback900
      description: R4 Router ID
      ip_address: 10.0.26.3
      subnet_mask: 255.255.255.255
      ospf_enabled: true
      passive: true
      stub: false
      ospf_area: 0