---
router_id: 10.0.28.129

ospf_interfaces:
  - name: GigabitEthernet1.900
    description: Link to R1
    ip_address: 10.0.28.1
    subnet_mask: 255.255.255.252
    ospf_enabled: true
    passive: false

  - name: Loopback0
    description: R1 Router ID
    ip_address: 10.0.28.129
    subnet_mask: 255.255.255.255
    ospf_enabled: true
    passive: true