---
router_id: 10.0.28.129

restconf:
  host: 10.8.2.5

bgp:
  asn: 65512

ospf:
  abr: true
  asbr: false

  ospf_areas:
    - area_id: 1
      type: stub


  ospf_interfaces:
    - name: GigabitEthernet1.900
      description: Link to R1
      ip_address: 10.0.28.1
      subnet_mask: 255.255.255.252
      ospf_enabled: true
      passive: false
      stub: false
      ospf_area: 1
      istagged: true
      vlan_tag: 900
      
    - name: Loopback900
      description: R1 Router ID
      ip_address: 10.0.28.129
      subnet_mask: 255.255.255.255
      ospf_enabled: true
      passive: true
      stub: false
      ospf_area: 0
      
