---
- name: Gather Device State
  hosts: "{{ target | default('ios_ospf_routers') }}"
  gather_facts: false
  strategy: free

  tasks:
    - name: Gather ospfv2
      cisco.ios.ios_ospfv2:
        state: gathered
      register: v2

    - name: Gather ospf_interfaces
      cisco.ios.ios_ospf_interfaces:
        state: gathered
      register: ospf_ifaces

    - name: Gather L3 interface configs
      cisco.ios.ios_l3_interfaces:
        state: gathered
      register: ip_ifaces

    - name: Gather L2 interface configs
      cisco.ios.ios_l2_interfaces:
        state: gathered
      register: ip_l2_ifaces

    - name: Write readable YAML
      ansible.builtin.shell:
        cmd: python /work/scripts/prettify.py "/work/backups/gathered/{{ inventory_hostname }}.yml"
        stdin: "{{ {'l3_ifaces': ip_ifaces.gathered, 'ospf_cfg': v2.gathered, 'ospf_ifaces': ospf_ifaces.gathered} | to_json }}"
      delegate_to: localhost
      changed_when: true
