# ============ KingCorp (65512) ============
[kc_core]
kc-hq-cor01 ansible_host=10.8.2.1
kc-hq-cor02 ansible_host=10.8.2.2
kc-hq-cor03 ansible_host=10.8.2.3

[kc_stub]
kc-hq-stb01 ansible_host=10.8.2.5

[kc_nssa]
kc-hq-nsa01 ansible_host=10.8.2.4

[kc_edge]
kc-hq-edg01 ansible_host=10.8.2.6

# ============ FlynnCorp (65513) ============
[fc_edge]
fc-hq-edg01 ansible_host=10.8.2.50
fc-hq-edg02 ansible_host=10.8.2.51

[fc_distro]
fc-hq-dst01 ansible_host=10.8.2.52

[fc_access]
fc-hq-acc01 ansible_host=10.8.2.53
fc-hq-acc02 ansible_host=10.8.2.54

# ============ Providers ============
[ktr_core]
ktr-p01 ansible_host=10.8.2.100
ktr-p02 ansible_host=10.8.2.101
ktr-p03 ansible_host=10.8.2.102
ktr-p04 ansible_host=10.8.2.103
ktr-p05 ansible_host=10.8.2.104
ktr-p06 ansible_host=10.8.2.105

[mrd_pe]
mrd-pe01 ansible_host=10.8.2.110

[mrd_core]
mrd-p01 ansible_host=10.8.2.111

[hcn_pe]
hcn-pe01 ansible_host=10.8.2.115

[hcn_core]
hcn-p01 ansible_host=10.8.2.116
hcn-p02 ansible_host=10.8.2.117

[znt_pe]
znt-pe01 ansible_host=10.8.2.120

[znt_core]
znt-p01 ansible_host=10.8.2.121

[crv_pe]
crv-pe01 ansible_host=10.8.2.125

[crv_core]
crv-p01 ansible_host=10.8.2.126

[nmb_core]
nmb-p01 ansible_host=10.8.2.130
nmb-p02 ansible_host=10.8.2.131

[vtq_pe]
vtq-pe01 ansible_host=10.8.2.135

[vtq_core]
vtq-p01 ansible_host=10.8.2.136

# ============ Datacenter (65520) ============
[dc_spine]
dc-den-spn01 ansible_host=10.8.2.150
dc-den-spn02 ansible_host=10.8.2.151

[dc_leaf]
dc-den-lef01 ansible_host=10.8.2.155
dc-den-lef02 ansible_host=10.8.2.156
dc-den-lef03 ansible_host=10.8.2.157

# ============ Shared ============
[edge]
inet-rtr01 ansible_host=10.8.2.254

# ============ Topology tree ============
[kingcorp:children]
kc_core
kc_stub
kc_nssa
kc_edge

[flynncorp:children]
fc_edge
fc_distro
fc_access

[datacenter:children]
dc_spine
dc_leaf

[meridian:children]
mrd_pe
mrd_core

[halcyon:children]
hcn_pe
hcn_core

[zenith:children]
znt_pe
znt_core

[corvid:children]
crv_pe
crv_core

[nimbus:children]
nmb_core

[vantiq:children]
vtq_pe
vtq_core

[ku_transit:children]
ktr_core

[tier1:children]
ku_transit

[tier2:children]
meridian
halcyon
zenith
corvid
nimbus
vantiq

[providers:children]
tier1
tier2

[customers:children]
kingcorp
flynncorp
datacenter

[lab:children]
providers
customers
edge

# ============ Function groups ============
[provider_edge:children]
mrd_pe
hcn_pe
znt_pe
crv_pe
vtq_pe

[provider_core:children]
ktr_core
mrd_core
hcn_core
znt_core
crv_core
nmb_core
vtq_core

[customer_edge:children]
kc_edge
fc_edge
dc_spine

[ospf_routers:children]
kingcorp

[bgp_routers:children]
providers
customer_edge

[ios_routers:children]
lab

[ios_switches:children]
dc_leaf
fc_access
fc_distro