
[ios_routers]
R1 ansible_host=10.8.1.100
R2 ansible_host=10.8.1.103
inet_rtr ansible_host=10.8.1.254

[ios_switches]
mgmt_sw ansible_host=10.8.1.104

[asa_firewalls]
FW1 ansible_host=10.8.1.102

[ios:children]
ios_routers
ios_switches

[ios:vars]
ansible_network_os=cisco.ios.ios

[asa_firewalls:vars]
ansible_network_os=cisco.asa.asa

[all:vars]
ansible_user=admin
ansible_password=admin
ansible_connection=network_cli
ansible_become=yes
ansible_become_method=enable
ansible_become_password=admin
